### ISSUE TITLE
Обоснование выбора инструментов и платформы для разработки

### ISSUE THREAD

**Issue by thisheavydyingsoul** [thisheavydyingsoul/coursework#10]

**Comment by thisheavydyingsoul** [comment]
Платформой для создания системы автоматизации работы сети компьютерных клубов будет .NET Core: Entity Framework, WPF Forms и ASP.NET, разработка будет происходить с помощью языка C#. СУБД, используемая при разработке - Microsoft SQL Server.

**Comment by thisheavydyingsoul** [comment]
О платформе .NET Core:
.NET - платформа разработки программного обеспечения, разрабатываемая компанией Microsoft с 2002 года. Основной целью при создании платформы было предоставление возможности создания различных типов приложений (web, desktop и пр.), которые также смогут запускаться на разных устройствах.
Преимущества:

1. Самое главное преимущество - среда выполнения Common Language Runtime (CLR), которая позволяет выбрать удобный язык программирования и выполнять код без изменений на различных платформах. 

2. Разнообразие языков программирования, компилируемых под данную платформу. 

3. Постоянные поддержка и обновления .NET Core от компании Microsoft.

4. Огромное количество готовых библиотек для выполнения различных задач.

5. Идеальный баланс между безопасностью и производительностью: разработчику нет необходимости беспокоиться о выделении памяти, потребление ресурсов аппаратного обеспечения и пр. - платформа берет эту задачу на себя и выполняет ее оптимально.

6. .NET Core предоставляет возможность для создания многих видов приложений, применяющихся в самых разнообразных сферах.

Недостатки платформы:

1. Ограниченный доступ к некоторым библиотекам и инструментам, которые доступны в .NET Framework.

2. Приложения, разработанные на базе .NET Framework также могут не работать на платформе .NET Core.

Несмотря на негативные аспекты, данная платформа является удобным и мощным инструментом для разработки приложений с совершенно разными целями, задачами и платформами развертывания.

**Comment by wldmr-key** [comment]
пойдет. Ссылки на источники будут? Почему подходит для твоей разработки не скажешь?
СУБД не будешь обосновывать?

**Comment by thisheavydyingsoul** [comment]
Все буду обосновывать, ссылки на сайты, которые не работают без впн необходимо присылать?

**Comment by thisheavydyingsoul** [comment]
Данная платформа подходит для работы, т.к. она позволяет развернуть систему на разных устройствах и с разными типами приложений.

**Comment by thisheavydyingsoul** [comment]
О WPF:
WPF - платформа, предназначенная для создания GUI, на которые не влияет разрешение. В WPF интерфейс строится с помощью векторного механизма визуализации, который способен использовать все преимущества современного графического аппарата. Преимущества данной платформы:

1. Независимость графики от разрешения устройства: единицей измерения является аппаратно-независимый пиксель, который масштабируется в соответствие с количеством точек на дюйм.

2. Высокая точность: координаты высчитываются с помощью чисел двойной точности с плавающей запятой.

3. Расширенная поддержка графики и анимации: платформа автоматически управляет сценами, что позволяет разработчику не заботиться о многих сложных аспектах.

4. Аппаратное ускорение: система использует ресурсы графического оборудования, что значительно снижает загруженность CPU.

Данная платформа используется в разработке т.к. с помощью нее можно создать пользовательский интерфейс, абстрагируясь от многих сложных аспектов графики, а также она является частью .NET, что разрешает вопрос о совместимости ее с основной платформой разработки.

**Comment by thisheavydyingsoul** [comment]
Об Entity Framework:
Entity Framework - решение для связи базы данных и приложения на платформе .NET.
Преимущества Entity Framework:

1. Упрощенный доступ к БД: платформа предоставляет высокоуровневый API для доступа к записям в БД.

2. Совместимость с различными СУБД, что позволяет легко переключаться между разными БД.

3. Поддержка транзакций: платформа позволяет выполнять операции БД в рамках транзакций, что значительно усиливает целостность данных.  

4. Автоматическое создание SQL запросов: Entity Framework автоматически создает SQL запросы на основе объектной модели, что позволяет разработчику избегать самостоятельного написания данных запросов.

Это далеко не все преимущества данной платформы, исходя из которых и было принято решение в выборе данной платформы для разработки системы.

**Comment by wldmr-key** [comment]
> Это далеко не все преимущества данной платформы, исходя из которых и было принято решение в выборе данной платформы для разработки системы.

а остальные преимущества, повлиявшие на решение, почему не заслужили упоминания?

Судя по тексту, мне в декабре стоит ждать транзакций и переключения между различными СУБД в твоем приложении? Ведь это повлияло на твой выбор? ;)

и да, анимацию тоже жду ))

> Все буду обосновывать, ссылки на сайты, которые не работают без впн необходимо присылать?

они, ведь, не экстремистские? )) тогда, почему бы нет?

**Comment by thisheavydyingsoul** [comment]
Об ASP.NET:
ASP.NET является популярной средой для разработки веб-приложений (в данной работе среда используется именно для веб-разработки). 
Преимущества данной платформы:

1. Основа - ООП: разработка на данной платформе ведется с помощью ООП, что позволяет по максимуму использовать преимущества данного подхода и сократить время для разработки.

2. Интеграция с Visual Studio IDE: совместимость с данной IDE является немаловажным фактором при выборе платформы для разработки, т.к. она является одной и той же для всех проектов в .NET.

С помощью ASP.NET можно создать веб-приложение, используя принципы ООП, в дополнение, данная платформа так же как и другие платформы, выбранные мной, является частью .NET.

Источник: https://senior.ua/articles/yavlyaetsya-li-aspnet-horoshim-vyborom-dlya-programmistov

**Comment by thisheavydyingsoul** [comment]
О Microsoft SQL Server:
MS SQL Server - широко известная система управления реляционными базами данных.
Ее основные преимущества:
1. Низкие требования к аппаратному обеспечению: производительность в данной СУБД будет как и на мощных персональных компьютерах, так и на слабых ноутбуках.

2. Совместимость с Entity Framework: данное преимущество является основным при выборе БД. 

3. Данная СУБД прекрасно интегрируется в приложения, созданные на основе .NET, что также является огромным плюсом.

4. Быстрое извлечение данных за счёт размера страниц.

Данная СУБД отлично подходит для разработки на платформах .NET, легко интегрируется с ними а также имеет высокую производительность даже на слабых ПК.

**Comment by thisheavydyingsoul** [comment]
>а остальные преимущества, повлиявшие на решение, почему не заслужили упоминания?

У данной платформы их просто очень много, я выделил основные

>Судя по тексту, мне в декабре стоит ждать транзакций и переключения между различными СУБД в твоем приложении? >Ведь это повлияло на твой выбор? ;)
>и да, анимацию тоже жду ))

Вообще, я думал, что у нас все по-взрослому и транзакции нужны. А насчет анимаций, хорошо, я понял, уберу)

Ссылки к источникам приложу

**Comment by thisheavydyingsoul** [comment]
Нечаянно исправил ваш комментарий поначалу, все вернул обратно

**Comment by wldmr-key** [comment]
> Как и было указано ранее

такие обороты употреблять без большой нужды не стоит

**Comment by thisheavydyingsoul** [comment]
спасибо, учту
