### ISSUE TITLE
Логическая схема

### ISSUE THREAD

**Issue by thisheavydyingsoul** [thisheavydyingsoul/coursework#11]

**Comment by thisheavydyingsoul** [comment]
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/ac53e7e0-f94a-49b3-b62d-8f1b14462bca)

**Comment by thisheavydyingsoul** [comment]
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/2996f1ea-e792-440b-b613-bfe0870f9e7d)

**Comment by thisheavydyingsoul** [comment]
Добавил новую сущность для отслеживания изменений админов

**Comment by thisheavydyingsoul** [comment]
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/d3add038-db5a-4bd5-82aa-b36105a6cbf0)
Добавил новую связь (кто-то же должен добавлять офисы?) и, похоже, у меня замкнулось кольцо, из-за чего СУБД и ругалась (что логично, ведь я с чего-то должен начинать наполнение БД, а у меня везде not-nullable внешние ключи) 
В общем, я их сделал nullable, но цикл все равно остается, можно ли так оставить или лучше изменить схему?

**Comment by wldmr-key** [comment]
> что логично, ведь я с чего-то должен начинать наполнение БД, а у меня везде not-nullable внешние ключи

Это, как раз, и было нелогично. Ключи в логе обязаны быть nullable, так как они взаимоисключающие (запись в логе относится только к одному из 4-5 объектов). Причина в этом, а не в мифических " чего-то должен начинать наполнение БД" или "замкнулось кольцо". Колец у тебя нет, так как "кольцевые" связи разного сорта

**Comment by thisheavydyingsoul** [comment]
В логах они nullable, но в таком случае возникает диллема:
У офиса должен быть лог, чтобы его создать нужен сотрудник, чтобы сделать сотрудника, должен быть офис и по кругу, разве не так?

**Comment by wldmr-key** [comment]
не так

во-первых ты принял решение записывать модификации сотрудникови всего остального в разные логи

как я понимаю,  Adm_username - это автор изменения. Пусть это будет Василий

Тогда, создается офис ХХХ - в логе появляется запись - Василий сделал ХХХ,
Если Василий создал Михаила и привязал его к ХХХ, то в логе изменений пользователей появляется запись, что Василий создал Михаила и запись, что Василий привязал его к ХХХ (этой связи у тебя, кста, нет)

Где кольцо-то?

Если ты предполагаешь, что для создания офиса сотрудник должен быть к нему привязан, то это ошибка. Офис может создавать только пользователь, не привязанный ни к чему (это своего рода флаг), либо пользователь у которого есть на это право (другой флаг - выбирай, какой из флагов тебе ближе)

**Comment by thisheavydyingsoul** [comment]
А, т.е. лучше убрать связь между админом и офисом?

**Comment by wldmr-key** [comment]
пуркуа? они же у тебя связаны с офисом по описанию предметной области, если я не ошибаюсь!

Но у тебя в описании нет разрешения неоднозначности, о которой я говорил в своем посте

**Comment by thisheavydyingsoul** [comment]
Ну вот я сейчас и подумал, что привязка сотрудника к офису не нужна, она никакой роли не играет, или я ошибаюсь? Да, по описанию предметной области связаны

**Comment by wldmr-key** [comment]
ну, как тебе сказать... Это опять о правах. Изменять состояние имущества офиса может либо только работник офиса, либо суперадмин, я думаю

**Comment by thisheavydyingsoul** [comment]
> что Василий создал Михаила и запись, что Василий привязал его к ХХХ (этой связи у тебя, кста, нет)

у меня administrator edits не только о создании, но и о любом изменении информации об админе

**Comment by wldmr-key** [comment]
> у меня administrator edits не только о создании, но и о любом изменении информации об админе

ты напишешь строку о том, что сотрудника привязали к офису ХХХ, но не отследишь целостность на уровне ключей

**Comment by wldmr-key** [comment]
что кстати показывает порочность идеи двух логов ))

**Comment by thisheavydyingsoul** [comment]
Я совсем не понимаю, почему у меня нет связи о том, что сотрудника привязали к офису, и почему я это никак не отслежу :(

**Comment by thisheavydyingsoul** [comment]
Решил попробовать сделать так (добавить Supervisor'а и для него отдельные логи), но как тогда эти supervisor'ы забиваются в систему? Для этого тоже нужно лог иметь? Они также изменяют и создают офисы

**Comment by wldmr-key** [comment]
о, нет!!!! только не усложняй схему!!!

давай на консультации обсудим!

**Comment by thisheavydyingsoul** [comment]
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/9e62909b-0472-44ca-99f1-0baaec5e74b1)
Новая схема

**Comment by wldmr-key** [comment]
так проще, во всяком случае

**Comment by thisheavydyingsoul** [comment]
Вопрос, наверное, в эту же issue, где хранить действующего админа? Предположение: создать статический класс, и там при каждом входе изменять инфу

**Comment by wldmr-key** [comment]
а, кто это? ))
и при чем тут статический класс?

**Comment by thisheavydyingsoul** [comment]
Администратор, от лица которого вносятся изменения

**Comment by wldmr-key** [comment]
а, у тебя только один человек в системе может работать в одно время? (если я правильно понял вопрос)

**Comment by thisheavydyingsoul** [comment]
На одном компьютере - да, вот конкретно в одном случае, когда я вхожу в приложение, я в этот момент должен как бы начинать учёт того, кто работает с данными

**Comment by wldmr-key** [comment]
нет, все это не так делается. Почитай про авторизацию и сессии. Ты "делаешь учет" всякий раз, когда получаешь запрос - проверяешь, кто это и, в зависимости от его прав, делаешь (или не делаешь) то или иное лдействие

**Comment by thisheavydyingsoul** [comment]
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/7d00b25d-35b8-4b9f-8187-a4ba2b29c6f4)
Окончательная логическая схема (изменения незначительные, я даже не уверен, что они есть, но пусть будет здесь как окончательная)
