### ISSUE TITLE
Перечень задач, подлежащих решению в процессе разработки

### ISSUE THREAD

**Issue by thisheavydyingsoul** [thisheavydyingsoul/coursework#12]

**Comment by thisheavydyingsoul** [comment]
Задачи, которые необходимо решить при разработке системы администрации сети компьютерных клубов.

1. Разработка пользовательского интерфейса для администраторов и клиентов клуба;
2. Проектирование и разработка базы данных;
3. Предоставление возможности доступа к данным, их вводу и редактированию;
4. Предоставление различного функционала в зависимости от ролей пользователей.

**Comment by wldmr-key** [comment]
норм

**Comment by wldmr-key** [comment]
если только ты еще и занимаешься процессом

> автоматизации работы библиотеки

**Comment by thisheavydyingsoul** [comment]
Глуповато получилось, буду третьим, еще есть место, я надеюсь

> если только ты еще и занимаешься процессом
> 
> > автоматизации работы библиотеки

**Comment by thisheavydyingsoul** [comment]
Кстати, у меня получается одна система или две раздельные? Если первую ее "часть" можно назвать "Система администрации", то как вторую? Система представления информации?

**Comment by wldmr-key** [comment]
на мой взгляд, это две компоненты одной системы
