### ISSUE TITLE
Физическая схема

### ISSUE THREAD

**Issue by thisheavydyingsoul** [thisheavydyingsoul/coursework#13]
Думаю, что данный вопрос относится именно к этой теме:
Долго борюсь с созданием БД уже, сначала сделал ее DB-First, но затем прочитал, что это влечет за собой большие ошибки при масштабном изменении самой БД, и начал делать code-first.
Так вот сам вопрос, так ли важны названия атрибутов уже при создании БД при помощи кода? Т.е., например, дублирование "id" (в коде то это в разных файлах + приходится прописывать вручную названия эти). Или также важно, чтобы такого дублирования не было?
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/503c1b53-5f60-4cb2-a386-97055edc89ca)

**Comment by wldmr-key** [comment]
дело вкуса - даже у меня в разных проектах и так, и так
Но я предпочитаю делать нормальные имена и прописывать entity вручную (если, вдруг, я им пользуюсь), так как я создаю БД по старинке ))

**Comment by thisheavydyingsoul** [comment]
При создании данной связи он выдает такую занимательную ошибку 
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/097c0035-474b-42c9-9d31-6938391197fc)
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/e149999b-761b-4e25-8fbd-9a1a0c71c03d)
Я не очень понимаю, в каком месте создается cycle, ну или же как из данной ситуации выйти

**Comment by wldmr-key** [comment]
решил проблему, как я понимаю?

**Comment by thisheavydyingsoul** [comment]
Нууу, я бы не сказал так, я просто убрал ограничения о необходимости внешних ключей, хороший ли это тон, если я все равно буду контролировать это в приложении?

**Comment by wldmr-key** [comment]
это плохой тон ))

**Comment by thisheavydyingsoul** [comment]
Вопрос: как лучше всего в моем случае сохранять картинки? Почитал, что по ссылке лучше всего, но в таком случае мне же придется хранить его на своем устройстве

**Comment by thisheavydyingsoul** [comment]
В каком типе хранит

**Comment by wldmr-key** [comment]
> Почитал, что по ссылке лучше всего

это неверно. В одних случаях так, в других - этак. Хранение вне БД - это потенциальная потеря целостности. Хранение в БД - это небольшая потеря в скорости и несколько больше возни в разработке.
Разумеется, в обоих случаях все хранится на сервере. На клиента в любом случае картинку отдает он

**Comment by thisheavydyingsoul** [comment]
Наконец, 
# физическая схема

## Таблица Administrators
  CREATE TABLE Administrators (
      Username varchar(20) NOT NULL,
      OfficeId int NOT NULL,
      Fullname varchar(50) NOT NULL,
      Password varchar NOT NULL,
      Phone varchar NOT NULL,
      Email varchar(50) NOT NULL,
      IsActive bit NOT NULL,
      IsHr bit NOT NULL,
      CONSTRAINT PK_Administrators PRIMARY KEY (Username),
      CONSTRAINT FK_Administrators_Offices FOREIGN KEY (OfficeId) REFERENCES Offices (Id)
  );

## Таблица Clients
   CREATE TABLE Clients (
      Username varchar(20) NOT NULL,
      Fullname varchar(50) NOT NULL,
      Password varchar NOT NULL,
      Phone varchar NOT NULL,
      Email varchar(50) NOT NULL,
      Balance int NOT NULL,
      CONSTRAINT PK_CLIENTS PRIMARY KEY (Username)
  );

## Таблица Devices
   CREATE TABLE Devices (
      Id int identity(1,1) NOT NULL,
      OfficeId int NOT NULL,
      Type varchar(20) NOT NULL,
      Name varchar(20) NOT NULL,
      Condition bit NOT NULL,
      DayRate int NOT NULL,
      NightRate int NOT NULL,
      Description varchar NOT NULL,
      Picture varbinary NOT NULL,
      CONSTRAINT PK_DEVICES PRIMARY KEY (Id),
      CONSTRAINT FK_DEVICES_OFFICES FOREIGN KEY (OfficeId) REFERENCES Offices
  );

## Таблица DevicesGames
   CREATE TABLE DevicesGames (
      DeviceId int NOT NULL,
      GameName varchar NOT NULL,
      CONSTRAINT PK_DEVICESGAMES PRIMARY KEY (DeviceId, GameName),
      CONSTRAINT FK_DEVICESGAMES_DEVICES FOREIGN KEY (DeviceId) REFERENCES Devices,
      CONSTRAINT FK_DEVICESGAMES_GAMES FOREIGN KEY (GameName) REFERENCES Games
  );

## Таблица Games
   CREATE TABLE Games (
      GameName varchar NOT NULL,
      Description varchar NOT NULL,
      Picture varbinary NOT NULL,
      CONSTRAINT PK_GAMES PRIMARY KEY (GameName)
  );

## Таблица Logs
   CREATE TABLE Logs (
      Id int IDENTITY(1,1) NOT NULL,
      Contents varchar NOT NULL,
      AdministratorId int NOT NULL,
      CONSTRAINT PK_LOGS PRIMARY KEY (Id),
      CONSTRAINT FK_LOGS_ADMINISTRATORS FOREIGN KEY (AdministratorId) REFERENCES Administrators
  );

## Таблица Offices
   CREATE TABLE Offices (
      Id int IDENTITY(1,1) NOT NULL,
      Adress varchar NOT NULL,
      CONSTRAINT PK_OFFICES PRIMARY KEY (Id),
  );

## Таблица Promos
   CREATE TABLE  Promos (
      Id int IDENTITY(1,1) NOT NULL,
      StartDate datetime NOT NULL,
      EndDate datetime NOT NULL,
      Coefficient int NOT NULL,
      Description varchar NOT NULL,
      Picture varbinary NOT NULL,
      CONSTRAINT PK_PROMOS PRIMARY KEY (Id),
  );

## Таблица Rents
   CREATE TABLE  Rents (
      Id int IDENTITY(1,1) NOT NULL,
      StartDT datetime NOT NULL,
      EndDT datetime NOT NULL,
      Coefficient int NOT NULL,
      Description varchar NOT NULL,
      ClientUsername varchar NOT NULL,
      DeviceId int NOT NULL,
      CONSTRAINT PK_RENTS PRIMARY KEY (Id),
      CONSTRAINT FK_RENTS_CLIENTS FOREIGN KEY (ClientUsername) REFERENCES CLIENTS,
      CONSTRAINT FK_RENTS_DEVICES FOREIGN KEY (DeviceId) REFERENCES Devices
  );

## Таблица Reviews
   CREATE TABLE  Reviews (
      RentId int NOT NULL,
      Contents varchar NOT NULL,
      Rating int NOT NULL,
      CONSTRAINT PK_REVIEWS PRIMARY KEY (RentId),
      CONSTRAINT FK_REVIEWS_RENTS FOREIGN KEY (RentId) REFERENCES RENTS,
  );

**Comment by wldmr-key** [comment]
Руками что ли писал? Или это entity такой умный?

Это как?
>CONSTRAINT PK_Administrators PRIMARY KEY (Username),
CONSTRAINT FK_Administrators_Offices **PRIMARY KEY** (OfficeId) REFERENCES Offices (Id)

И почему есть таблицы без первичных ключей?

**Comment by thisheavydyingsoul** [comment]
Руками писал, отсюда и ошибка небольшая вылезла

> Это как?
> 
> > CONSTRAINT PK_Administrators PRIMARY KEY (Username),
> > CONSTRAINT FK_Administrators_Offices **PRIMARY KEY** (OfficeId) REFERENCES Offices (Id)

Вы правы, перечитал документацию, изначально показалось, что ключевое слово Identity создает ограничение для первичного ключа, исправил
> И почему есть таблицы без первичных ключей?
