### ISSUE TITLE
Алгоритмы обработки информации

### ISSUE THREAD

**Issue by thisheavydyingsoul** [thisheavydyingsoul/coursework#15]

**Comment by thisheavydyingsoul** [comment]
Административная часть системы представляет собой интерфейс между администратором и базой данной, который позволяет ему добавлять, просматривать и изменять необходимые данные. 
Примером операции добавления является внесение новой игры в базу данных:

public void AddNewGame(object sender, RoutedEventArgs e)
        {
            if (!DataHelper.CheckActivity())
            {
                Close();
                return;
            }
            using ComputerClubDBContext context = new ComputerClubDBContext();
            Administrator currentAdmin = (Administrator)context.Administrators.Where(a => a.Username == DataHelper.username).FirstOrDefault();
            string name = namebox.Text;
            string description = descriptionbox.Text;
            if (String.IsNullOrEmpty(name) || String.IsNullOrEmpty(description) || game.Picture == null) 
            {
                MessageBox.Show("Введите все необходимые значения!");
                return;
            }
            game.Name = name;
            game.Description = description;
            context.Add(game);
            Log log = new Log()
            {
                Contents = String.Format("{0}: добавил новую игру: {1} {2}", DataHelper.username, game.Name, DateTime.Now),
                Administrator = context.Administrators.Where(
                    a => a.Username == DataHelper.username).FirstOrDefault()
            };
            context.Add(log);

            //Checking if something goes wrong
            if (DataHelper.TrySaving(context))
            {
                MessageBoxResult result2 = MessageBox.Show("Игра успешно добавлена", "Успех", MessageBoxButton.OK);
                if (result2 == MessageBoxResult.OK)
                    Close();
            }
        }

Блоки работы алгоритма:
1. Проверка прав доступа текущего администратора. Если прав нет - сообщение об этом и закрытие окна.
2. Проверка на то, что все необходимые поля заполнены. Если нет - сообщение пользователю об этом и возвращение его к заполнению
3. Добавление записи о добавленной игре в таблицу логов
4. Попытка сохранения добавленных записей в базе данных. Вывод об ошибке, если она возникнет
##

Вывод данных воспроизводится с помощью таблицы DataGrid, в которую передается массив данных:
Game[] games = context.Games.Include(g => g.DevicesGames).ThenInclude(dg => dg.Device).ToArray();
GamesList.ItemsSource = games;

Затем, выбрав определённую игру, можно просмотреть информацию о ней в отдельном окне:
private void ShowGameDescription(object sender, RoutedEventArgs e)
        {
            Game selected = (Game)GamesList.SelectedItem;
            GameDescription gd = new GameDescription(selected);
            gd.Show();
        }

##

Примером операции обновления информации является добавления устройства в список устройств, на которые данная игра установлена:

 void OnChecked(object sender, RoutedEventArgs e)
        {
            Administrator currentAdmin = context.Administrators.Where(a => a.Username == DataHelper.username).FirstOrDefault();
            if (!DataHelper.CheckActivity())
            {
                Close();
                return;
            }
            CheckBox checkBox = sender as CheckBox;
            KeyValuePair<Device, bool> kvp = (KeyValuePair<Device, bool>)checkBox.DataContext;
            int deviceId = kvp.Key.Id;
            if (context.DevicesGames.Where(dg => dg.DeviceId == deviceId  && dg.GameName == game.Name).FirstOrDefault() != null) return;
            context.Add(new DeviceGame()
            {
                DeviceId = deviceId,
                GameName = game.Name
            });
            context.Add(new Log()
            {
                Administrator = currentAdmin,
                Contents = String.Format("{0} установил {1} на {2} с ID: {3} {4}", currentAdmin.Username, game.Name, kvp.Key.Name, deviceId, DateTime.Now)
            });
            DataHelper.TrySaving(context);
            changedhandler();
        }

Основные блоки работы алгоритма:
1. Проверка прав доступа администратора. Если прав нет - сообщение об этом и закрытие окна.
2. Проверка, есть ли уже запись об установке игры на выбранном устройстве. Если запись существует - сообщить об этом.
3. Добавление записи в таблицу логов.
4. Попытка сохранить данные в БД. Сообщить об ошибке при ее возникновении.

**Comment by thisheavydyingsoul** [comment]
Стоит ли тут упоминать веб-часть? Алгоритмы мало чем отличаются там

**Comment by wldmr-key** [comment]
> Стоит ли тут упоминать веб-часть? Алгоритмы мало чем отличаются там

не стоит, и так нормально. Но могут придраться  ктому, что, согласно описанию у тебя алгоритм линейный, а он ветвится

**Comment by thisheavydyingsoul** [comment]
Вы про описание блоков?

**Comment by wldmr-key** [comment]
ага

**Comment by thisheavydyingsoul** [comment]
Как, например, тут?

> Блоки работы алгоритма:
> 
> 1. Проверка прав доступа текущего администратора. Если прав нет - сообщение об этом и закрытие окна.
> 2. Проверка на то, что все необходимые поля заполнены. Если нет - сообщение пользователю об этом и возвращение его к заполнению
> 3. Добавление записи о добавленной игре в таблицу логов
> 4. Попытка сохранения добавленных записей в базе данных. Вывод об ошибке, если она возникнет

**Comment by wldmr-key** [comment]
вполне

**Comment by thisheavydyingsoul** [comment]
Обновил описание блоков
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/71dd9406-ecca-4e40-a0bd-73d33fb00eb2)
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/89056c70-c837-4d12-b1d3-4593aac273a1)
