### ISSUE TITLE
Разработка интерфейса взаимодействия пользователя с системой

### ISSUE THREAD

**Issue by thisheavydyingsoul** [thisheavydyingsoul/coursework#16]

**Comment by thisheavydyingsoul** [comment]
Взаимодействие пользователя с системой производится с помощью веб-интерфейса, основным элементом которого является html-страница, стилизованная с помощью css. 
На страницах элементами управления являются кнопки переадресации на другую страницу и кнопки передачи формы в контроллеры. 

В системе есть header и body блоки.
Блок header доступен и одинаков на каждой странице, кроме страниц входа и регистрации. С помощью нее пользователь может перемещаться по частям системы для просмотра нужной ему информации.
В блоке расположены кнопки: 
1. Название сети клубов, при нажатии на которую выполняется переход на страницу адресов.
2. Адреса - с аналогичной функцией.
3. Акции, устройства, игры, аренды - переход на страницы с информацией из соответствующих таблиц бд.
4. Изменить профиль - переход на страницу изменения данных авторизованного пользователя.
5. Пополнить баланс - переход на страницу пополнения баланса.
Также справа в блоке располагается информация о текущем балансе пользователя.
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/8360ab93-b617-45b7-8279-7ba9bb07d830)

В блоке body находится страница, выбранная пользователем, с помощью header-блока навигации, каждая страница уникальна


Адреса
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/4f63e116-6e09-44c1-82b7-4b8d438bfeae)

#
Акции
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/bec325c4-ca64-42fd-a41f-4c689b1fc67a)

#
Устройства
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/0a5b197e-6e89-4eb1-9239-40f40871f7f5)

#
Игры
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/1bd493e6-f700-4224-8f0e-ba900c1905bb)

#
Аренды
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/75f04e05-b8f7-482d-90d0-b583d351cbad)

#
Изменение профиля
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/3c428475-bc22-4e31-be24-405a4549386b)

#
Пополнение баланса
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/245daace-182d-4074-91e9-0cc483571ff4)

**Comment by thisheavydyingsoul** [comment]
Необходимо ли в проектно-конструкторской части то же самое показывать для админской части?

**Comment by wldmr-key** [comment]
Нормально. Да, и для админской тоже желательно

**Comment by wldmr-key** [comment]
я бы советовал общие принципы дизайна вынести отдельно

**Comment by thisheavydyingsoul** [comment]
Тогда изменил список кнопок в сообщении выше и буду делать для админов

**Comment by thisheavydyingsoul** [comment]
Административная часть системы спроектирована с помощью WPF и паттерна MVVM. На главных окнах (как для работника с сотрудниками, так и для работника офиса) также есть общий header-блок с разделами, позволяющими осуществлять навигацию между таблицами и, в случае HR-работника, статистикой, а также строка для поиска по одному или нескольким параметрам. Как и в случае с клиентской версией, у основных окон присутствует body часть, в которой представлен список записей выбранной таблице. В footer-блоке располагается кнопка добавления записи в выбранную таблицу.

Пример Header-блока (здесь и далее окно работника отдела кадров)
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/5e4d06a8-c3aa-4ddc-9bcd-9a92eee532d5)
#
Пример body-блока 
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/624b7e0e-7c80-46f6-8ad1-e69b1872779d)
#
Пример footer-блока
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/f817da58-e040-4417-ad15-3bac93279f46)

# 
Также в административном приложении присутствуют вспомогательные окна добавления, изменения и просмотра записей в базе данных.
Примеры таких окон:
Добавление игры
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/1b15742c-28db-4094-acde-7b29d65cc13c)

# 
Изменение данных об игре
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/f8200417-9f78-4fd2-b559-adf87ad22756)

#
Просмотр данных об игре
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/130f223d-fe67-4133-bb54-4d0978fb3911)
