### ISSUE TITLE
Написать оформленное ТЗ

### ISSUE THREAD

**Issue by thisheavydyingsoul** [thisheavydyingsoul/coursework#2]

**Comment by thisheavydyingsoul** [comment]
1.1 Общие сведения
1.1.1 Полное наименование системы:
Приложение для посетителей или работников сети компьютерных клубов.

1.1.2 Наименование организации-заказчика, разработчика системы:
Заказчик: КФ МГТУ им. Н.Э. Баумана
Разработчик: Студент КФ МГТУ им. Н.Э. Баумана группы ИУК5-52Б Изранов К.С.

1.1.3 Плановые сроки начала и окончания работы по созданию системы:
Плановый срок начала работ - 5 сентября 2023 года
Плановый срок окончания работ - 1 декабря 2023 года


1.2 Назначение и цели создания системы
1.2.1 Назначение системы: 
Система предназначена для хранения данных о посетителях, упрощения их посещения, а также для удобного предоставления необходимой информации для сотрудников.

1.2.2 Цели создания системы:
Система создается для автоматизации работы филиалов компьютерного клуба.


1.3 Требования к системе
1.3.1 Требования к системе в целом:
1.3.1.1 Требования по эргономике и технической эстетике:
Интерфейс системы не должен вводить пользователя в заблуждение, содержать элементы, функционал которых отсутствует или не соответствует пояснению в интерфейсе. 
Интерфейс должен быть понятен и не перегружен графическими элементами.


1.3.2 Требования к функциям (задачам), выполняемым системой:
- Авторизация в приложении
- Отображение контента в приложениях как на телефоне, так и на устройствах внутри филиалов.
- Удобная функция бронирования
- Быстрая функция оплаты
- Управление профилем
- Система отзывов о пользователях, сотрудниках и филиалах.
- Добавление времени, устройства и (или) филиала в раздел "Избранное"
- Для сотрудников: Предоставление необходимой информации о всех устройствах и посетителях в филиале в удобном и понятном виде
- Система уведомлений об окончании оплаченного времени
- Система уведомлений о приближении времени бронирования
- Опрос о посещении клуба вблизи времени бронирования ("Придете ли вы в то время и дату, на которые вы забронировали устройство?")

1.3.3 Требования к видам обеспечения
1.3.3.1 Требования к лингвистическому обеспечению системы
Средством описания предметной области, так же, как и средством взаимодействия пользователя с системой является русский язык

1.3.3.2 Требования к входным и выходным данным
Входными данными в систему является уникальный идентификатор (nickname), который пользователь выбирает себе сам, и пароль, который пользователь также придумывает себе сам. Выходными данными для посетителя являются: необходимая информация об устройстве пользования, оставшемся времени, возможности (или невозможности) продлить время. Для сотрудника: необходимая информация об устройствах филиала, а также о посетителях, присутствующих в филиале на данный момент. 

1.3.3.3 Требования к программному обеспечению системы (тут пока не определился, нужно ли с этим определяться так рано?)...


1.4 Состав и содержание работ по созданию (развитию) системы
1. Утверждение темы, задания на разработку, технического задания. Оформление ТЗ. Описание предметной области и требований к системе. Концептуальная схема. Прототип или скетчи интерфейса.

2. Оформление введения и исследовательской части. Обоснование выбора БД, логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД.

3. Оформление проектно-конструкторской части. Демонстрация работающего приложения. Презентация. Тестирование и отладка приложения. Разработка эксплуатационной документации. 

4. Завершающее оформление документации согласно требованиям ГОСТ. Все ошибки и проблемы устранены. Подготовка доклада. Защита курсовой работы.


1.5 Порядок контроля и приёмки системы
Система разрабатывается с применением тестирования работоспособности функционала. При добавлении новых функций предыдущие тесты должны сохранять работоспособность.
Приёмка работы осуществляется комиссией КФ МГТУ им. Н.Э. Баумана кафедры ИУК5


1.6 Требования к документированию 
Требуется предоставить:
a) Техническое задание в соответствии с ГОСТ 34.602-89
b) Расчетно-пояснительную записку, включающую в исследовательскую часть, проектно-конструкторскую часть и проектно-технологическую часть, включающую в себя руководство пользователя и руководство программиста (администратора).
Расчетно-пояснительная записка выполняется с учетом требований, предусмотренных ГОСТ 7.32-2001 и 2.105-95.

**Comment by wldmr-key** [comment]
> Назначение системы

для кого она?!

> Цели создания системы:

а зачем она нужна, автоматизация? Что достигается?

все остальное - отлично

**Comment by thisheavydyingsoul** [comment]
Я исправил, вам же на это тоже приходят уведомления?

**Comment by wldmr-key** [comment]
нет, на edit уведомлений не посылается, поэтому, лучше или писать новый комментарий (можно только из исправленных пунктов - так лучше) или, в крайнем случае, уведомлять (мне , тогда, придется вспоминать или смотреть, что было)

**Comment by wldmr-key** [comment]
Можешь посмотреть на мой предыдущий комментарий и понять, как для меня выглядят исправления

**Comment by wldmr-key** [comment]
и, да, назначение и цели сильно лучше не стали ))

**Comment by thisheavydyingsoul** [comment]
1.2.1 Назначение системы:
Система предназначена для сотрудников и посетителей компьютерных клубов, она будет помогать им выполнять задачи:
Учет устройств в филиале
Выполнение бронирования
Выдача необходимой информации о посетителях сотруднику филиала
Можно ли тут ставить и т.д. (т.п.)?

1.2.2 Цели создания системы:
Система создается для полной или частичной автоматизации функций, указанных в пункте 1.2.1

**Comment by wldmr-key** [comment]
> Можно ли тут ставить и т.д. (т.п.)
здесь можно

> Система создается для полной или частичной автоматизации функций, указанных в пункте

не для этого. Система создается для снижения расходов клуба за счет полной или частичной автоматизации

**Comment by thisheavydyingsoul** [comment]
1.2.2 Цели создания системы:
Система создается для снижения расходов клуба, за счет полной или частичной автоматизации функций, указанных в пункте 1.2.1


//Но разве система не может увеличить расходы, но увеличить быстродействие?

**Comment by thisheavydyingsoul** [comment]
Хотя, в таком случае увеличится количество "успешных сделок" и увеличится прибыль

**Comment by wldmr-key** [comment]
всегда можо сказать, что недополученная прибыль - это расходы ))

**Comment by thisheavydyingsoul** [comment]
Тогда теперь эти пункты верны?

**Comment by wldmr-key** [comment]
ага

**Comment by thisheavydyingsoul** [comment]
Тогда изменил в первой записи все

**Comment by thisheavydyingsoul** [comment]
У меня все же вопрос по этому пункту, вам в ЭОС прям с таким заливать?
> 1.3.3.3 Требования к программному обеспечению системы (тут пока не определился, нужно ли с этим определяться так рано?)...

**Comment by wldmr-key** [comment]
в реальной жизни в таких ситуациях либо опускают этот пункт, либо пишут "согласуются Исполнителем и Заказчиком на этапе ..."

**Comment by thisheavydyingsoul** [comment]
Тогда убираю этот пункт и закрываю issue, благодарю за подсказку
