### ISSUE TITLE
Написать предварительное описание предметной области и требований к системе

### ISSUE THREAD

**Issue by thisheavydyingsoul** [thisheavydyingsoul/coursework#3]

**Comment by thisheavydyingsoul** [comment]
Предметная область - сеть компьютерных клубов с множеством филиалов. У каждого филиала есть штат сотрудников, определенный набор техники, а также своя "кухня" (примитивная, в ней сотрудники смогут разогреть уже готовую, упакованную еду или сварить кофе/чай для посетителей). В сети клубов можно арендовать следующие устройства: персональный компьютер, консоль, шлем виртуальной реальности и многое другое, что необходимо для работы или развлечения, для всего этого нужно вести учет. Также, необходимо вести учет для продуктов на кухне, чтобы не возникало неприятных ситуаций, как например: гость заказал какое-то "блюдо", оплатил его, а потом выясняется, что именно такого "блюда" сейчас нет в наличии, и придется искать способы решения данной проблемы, что очень неприятно как гостю, который будет тратить на это время, что сотруднику. Также посетитель не может заранее узнать, будет ли свободен компьютер с нужной ему программой/игрой, он не может его забронировать. (Вот дальше не уверен, нужно ли это в предметной области или нет, но в первой лабораторной по моделям данных я это написал). Вышеописанные проблемы поможет решить автоматизация работы сети компьютерных клубов.

**Comment by thisheavydyingsoul** [comment]
К данной автоматизированной системе выдвигаются следующие требования:
1. Сбор и хранение данных о посетителях.
2. Ведение учета техники и продуктов.
3. Слежка, надсмотр, контроль? за работой сотрудников. (По-английски красиво слово supervision, русские аналоги звучат все очень страшно)
4. Автоматизация и ускорение бронирования компьютера, а также поиска необходимой программы/игры.
Маловато вроде вышло, стоит больше? Правильно ли я вообще понял задачу по требованиям?

**Comment by wldmr-key** [comment]
Мне кажется, ты зря приплел сюда продукты. По логике вещей тогда компьютерный клуб должен приобретать лицензию (плюс прочие необходимые ограничения) на общественное питание. Брось, мой совет...

не хватает сущостей - пусть посетители пишут отзывы, заказы, пожелания; устраивай акции; соревнования, в конце концов... А по мне и так норм ))

Слежка, надсмотр, контроль - контроль

Автоматизация и ускорение  - зачем? просто бронирование

**Comment by thisheavydyingsoul** [comment]
Изменил описание и добавил пункты к требованиям

**Comment by thisheavydyingsoul** [comment]
У меня кандидатов, к сожалению, нет

**Comment by GeneralPechenka** [comment]
Может быть, стоит добавить, что входит в обязанности сотрудников, работающих с системой, как производится учёт всего скарба и пр?

**Comment by thisheavydyingsoul** [comment]
Изменил требования по сотрудникам, будет храниться только контактная информация, их должность и зарплата.

**Comment by wldmr-key** [comment]
Попробуй два своих текста сделать более связными и эпичными

описание предметной области разбить на смысловые абзацы и подробнее описать неоднозначные сущности и атрибуты (акции, например, или характеристики оборудования)

требования - опять-таки сделать более конкретными, чтобы из них очевидно следовала концептуальная схема

Например

Сбор и хранение данных о посетителях.

Система должна хранить контактную информацию посетителей (фио, емейл, телефон), а также информацию для авторизации (логин, хеш пароля). _идеально обосновать зачем это нужно одним предложением_

И так далее

**Comment by thisheavydyingsoul** [comment]
Обновил описание предметной области и пункты требований

**Comment by thisheavydyingsoul** [comment]
Внес изменения, отталкиваясь от концептуальной схемы 
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/5816429d-d466-45f3-ad74-3fa43c103fa8)

**Comment by wldmr-key** [comment]
хеширование пароля это не страшно ))

**Comment by thisheavydyingsoul** [comment]
Тогда здесь, в схеме и скетчах все ок?

**Comment by wldmr-key** [comment]
скажем, что при поверхностом взгляде я проблем не обнаружил

**Comment by thisheavydyingsoul** [comment]
Ну я вроде долго над всеми думал (и не один), тогда закрываю все issues
