### ISSUE TITLE
Выполнить предварительный анализ аналогов

### ISSUE THREAD

**Issue by thisheavydyingsoul** [thisheavydyingsoul/coursework#4]

**Comment by thisheavydyingsoul** [comment]
К сожалению не помню, что вы советовали тем, у кого с этим могут возникнуть трудности. У меня просто нет возможности эти аналоги рассмотреть, у нас в Калуге нет прям сетей компьютерных клубов, а всё программное обеспечение необходимо смотреть прямо на месте, и я даже не уверен, что это можно назвать аналогами, лично мне кажется, что тут все создается с индивидуальным подходом к каждому клубу или сети.

**Comment by wldmr-key** [comment]
набери в поисковой строке гугла
управление сетью компьютерных клубов

))

**Comment by thisheavydyingsoul** [comment]
Да, нашел аналоги, если их можно так назвать, но они для одного клуба, а не для сети. Допустим, это подойдет, сколько примерно надо рассмотреть, 2-3?

**Comment by wldmr-key** [comment]
>  но они для одного клуба, а не для сети

это будет твоим выигрышным качеством

я бы сказал 3 - 4

Не забывай ссылки на источники и относительно объективные отзывы

**Comment by thisheavydyingsoul** [comment]
1. SmartShell:
* База данных клиентов
* Защита от нежелательных действий
* Контроль техсостояния ПК
* Логирование процессов
* Онлайн-бронирование мест
* Отслеживание действий персонала
* Создание программ лояльности
* Таск-менеджер
* Управление игровыми местами
(По описанию с https://a2is.ru/catalog/programmy-dlya-kompyuternogo-kluba/smartshell)
Средний рейтинг 3.75, один резко негативный отзыв, рассказывающий о том, что программа сырая, но не ссылающийся ни на что конкретное, также положительных отзыва с оценкой 5, которые говорят о хорошей поддержке, хорошем интерфейсе программы, а также о регулярных обновлениях.
2. CyberSoft:
* База данных клиентов
* Защита от нежелательных действий
* Контроль техсостояния ПК
* Логирование процессов
* Онлайн-бронирование мест
* Отслеживание действий персонала
* Создание программ лояльности
* Таск-менеджер
* Управление игровыми местами (да, предлагают те же функции 1 в 1)
Средний рейтинг низкий, отзывов с рейтингом всего 2, один пишет, что все отлично и ставит 5, а другой о том, что связь с поддержкой ужасная, на английском, отвечают долго, а также обвиняют во всех проблемах клиента. В какой-то момент система упала, все данные пропали и, опять же, обвинили клиента в том, что он не делал бэкапы.
На другие системы отзывов вообще нет, поэтому не вижу смысла их рассматривать. Эта тема видимо совсем непопулярна

Основное преимущество моей системы в том, что она ведет учет за различными филиалами данного клуба, т.е. подключается к сети, а не к единичным клубам.

**Comment by wldmr-key** [comment]
все хорошо, но попробуй написать более связный и развернутый текст

**Comment by GeneralPechenka** [comment]
> Средний рейтинг 3.75, один резко негативный отзыв, рассказывающий о том, что программа сырая, но не ссылающийся ни на что конкретное, также положительных отзыва с оценкой 5, которые говорят о хорошей поддержке, хорошем интерфейсе программы, а также о регулярных обновлениях.

Я бы привёл цитаты пользователей и указал бы источник, который есть.

Ещё было бы хорошо написать общую информацию об аналогах, а не выкатить список из их особенностей.

Ещё бы я перечислил недостатки аналогов, если они есть. Потому что у тебя только их особенности и, видимо, преимущества.

**Comment by thisheavydyingsoul** [comment]
1. Senet.
Самая популярная на данный момент система управления компьютерным клубом, принцип ее работы основан на облачных технологиях, а данные хранятся на серверах Microsoft в Европе. Из этого вытекает первый минус: необходимость постоянного подключения к интернету. Еще одним недостатком я выделю цену: пользование данной системы стоит намного дороже, чем пользование ее аналогами. Вывод: система не подходит для начинающих проектов, т.к. она достаточно дорогая. 

2. Gizmo.
Проект, который разрабатывает небольшая группа людей из Греции и Санкт-Петербурга, в отличие от первой в данном списке системы, Gizmo разворачивается на локальном компьютере в самом клубе. По стоимости подходит и для бюджетных клубов. Из минусов стоит выделить время работы тех. поддержки: в связи с малым штатом разработчиков она состоит всего из 2 человек и отвечает только в рабочее время. Из описания на сайте так же следует, что управлять клубом удаленно с помощью данной системы тоже не получится, так что это тоже минус. 


3. GameClass.
Данная система управления в первую очередь отличается доступностью: она полностью бесплатна, что является преимуществом над остальными системами.  Но отсюда вытекают и следующие, негативные, качества данной системы: медленное развитие (на одном энтузиазме далеко не уедешь), нестабильность работы, а также качество самого приложения. Минусов тут целый список: система не обновлялась аж с 2013 года (и тем не менее в статье, прикрепленной ниже, она находится в топ 5), у нее нет техподдержки, и она не поддерживает новые игры и обновления Windows. Вывод: даже бесплатно, такая система скорее принесет убытки для одного клуба.
Источник: https://dasclub.ru/%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B-%D0%BF%D0%BE-%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8E-%D0%BA%D0%B8%D0%B1%D0%B5%D1%80-%D0%BA%D0%BB%D1%83%D0%B1%D0%B0%D0%BC/

Сравнивая мою систему с вышеперечисленными, я могу отметить, что только одна из них (Senet) позволяет управлять целой сетью компьютерных клубов, но при этом она является дорогой, что и будет моим преимуществом. Также моя система будет способна разворачиваться в локальной сети, что, как по мне, дает большую свободу в действиях о защите и распределении данных, чем только облачное хранилище.

**Comment by GeneralPechenka** [comment]
добавь к ним ещё особенности и преимущества, которые ты писал раньше. Написал сейчас гораздо лучше, чем было. Попробуй найти скрины их интерфейсов в инете, и вставь.

**Comment by wldmr-key** [comment]
> первый минус: необходимость постоянного подключения к интернету.

???!!!

> на одном энтузиазме далеко не уедешь

постарайся вычистить все подобные пассажи

> Сравнивая мою систему

убери первое лицо

Реально стало намного лучше

**Comment by GeneralPechenka** [comment]
Смотри, у тебя сначала идут плюсы, а потом описание аналога. Я бы поменял их местами, чтобы сначала было описание. Потому что правильнее идти от общего частному, а не наоборот. Попробуй сделать так: описание - скриншот - плюсы - минусы.

> необходимость постоянного подключения к интернету

Разве это минус?

**Comment by thisheavydyingsoul** [comment]
Обновил, неправильно выразился про интернет. Порядок мне кажется вполне себе хороший. Вроде везде убрал первое лицо и такие обороты речи.

**Comment by GeneralPechenka** [comment]
>  Из этого вытекает первый минус: хранение и целостность данных совсем не зависит от клиента

Кто такой клиент?  Как он должен влиять на целостность данных и их хранение?
