### ISSUE TITLE
Создать концептуальную схему данных предметной области

### ISSUE THREAD

**Issue by thisheavydyingsoul** [thisheavydyingsoul/coursework#5]

**Comment by thisheavydyingsoul** [comment]
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/6de95774-58f9-4c62-bac4-1413b60f8458)

**Comment by wldmr-key** [comment]
обрати внимание, твоя схема не может быть нарисована человеком, который не общался с тобой, а только прочитал твое описание предметной области (и требований к системе)

Вместе с тем, ряд понятий из описания и требований здесь отсутствует. Бронирование, например...

**Comment by thisheavydyingsoul** [comment]
Очень интересный вопрос: 
Схема уже и так получается достаточно большой, но я еще не изобразил на ней программы, игры и лицензии. Что мне стоит сделать с этим? Лучше убрать их вообще из описания и забыть, действительно добавлять и реализовывать или же сделать сноску о том, что это было бы уже много для реализации?
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/c3a133b3-9432-461f-bc35-13c164bff28d)

**Comment by wldmr-key** [comment]
поразмыслим...

чем бронирование принципиально отличается от аренды?
и то, и другое связано с экземпляром и посетителем (у тебя не так, но это ошибка)
разве что статусом?

ты привязываешь акции к экземплярям техники... Как это будет выглядеть в приложении? Кликать на каждый экземпляр? Мне кажется, акции распространяются на категории техники и/или филиалы. Поэтому, возможно, более правильным было бы в экземпляре техники хранить регулярную цену, а при аренде/бронировании пересчитывать с учетом акций и, возможно, персональных скидок

Программы, игры и лицензии - это не одна сущность?

Проблема думаю не в количестве сущностей (ну что тебе лишний create table написать!), а в сложности приложения - это ты сам должен оценнить свой потенциал

**Comment by thisheavydyingsoul** [comment]
Про бронирование и аренду согласен, я долго гад этим думал, но до этого не додумал
А про акции - они привязаны к технике отдельно, кликать на каждую не нужно, там будет "содержание", которое будет рассказывать о том, к чему они относятся, а также там будет поле с коэффициент скидки, на который и будет умножать цена

**Comment by thisheavydyingsoul** [comment]
Тогда концептуальная схема будет выглядеть так:
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/16dd2887-335e-4948-8477-d03528735b12)
Сущности:
1. Посетители:
* ФИО
* Почта
* Номер телефона

2. Аренды:
* Дата и время начала
* Дата и время окончания

3. Отзывы:
* Дата и время публикации
* Рейтинг (от 0 до 10)
* Содержание

4. Экземпляры техники:
* Тип
* Название
* Состояние
* Описание
* Фотография
* Тариф руб./час

5. Филиалы:
* Адрес
* Рейтинг

6. Сотрудники:
* ФИО
* Номер телефона 
* Почта
* Зарплата
* Фотография

7. Акции:
* Размер скидки
* Дата начала
* Дата окончания

8. Акции-экземпляры сразу решил сделать сущность для устранения М-М

9. Игры:
* Название

10. Игры-экземпляры также как и акции-экземпляры.
Также это немного не соответствует описанию предметной области, например, я решил убрать лицензии (в реальном мире пользователи заходят на компьютеры под своими аккаунтами в разных дистрибьютерах игр, так что важно лишь факт установки игры на компьютер). Сейчас пойду менять и описание с требованиями

**Comment by wldmr-key** [comment]
все ли атрибуты у тебя упомянуты в описании предметной области

как  ты осуществляешь контроль деятельности сотрудников?

как отличаешь аренду от бронирования?

какова кратность связи посетители - аренды?

в чем проявляется связь между акциями и экземплярами техники (приведи пример акции)?

**Comment by thisheavydyingsoul** [comment]
> все ли атрибуты у тебя упомянуты в описании предметной области - нет, стоит добавить такие атрибуты как ФИО и фото для сотрудников, например?

> как ты осуществляешь контроль деятельности сотрудников? - хороший вопрос, думаю, стоит добавить отработанные часы, для этого наверное добавить еще сущность "Месяцы" 😢 

> как отличаешь аренду от бронирования? - Бронирование по факту та же аренда, с возможностью отмены, но за час до начала срока аренды (бесплатно)

> какова кратность связи посетители - аренды? - Да, неправильно поставил это в схеме, исправлю и обновлю картинку в комментарии выше

> в чем проявляется связь между акциями и экземплярами техники (приведи пример акции)? - Например создается акция со временем от 21 сентября до 28 со скидкой на все устройства, в запросе это будет выглядеть как создание новых сущностей акции-экземпляр, вяжущиеся к этой акции, соответственно, и ко всем сущностям типа "экземпляры техники" (если бы акция была для отдельных сущностей, то она привязывала бы с условием "тип устройства = *такому-то*). При вычислении цены на аренду, проверяются все привязанные к данному экземпляру акции-экземпляры и смотрят на дату, если есть такие акции, которые все еще действуют, то цена за тариф умножается на коэффициент.

**Comment by wldmr-key** [comment]
> > все ли атрибуты у тебя упомянуты в описании предметной области
> 
> Нет, стоит добавить такие атрибуты как ФИО и фото для сотрудников, например?

желательно... А зарплата здесь каким боком? зачем она нужна?

> > как ты осуществляешь контроль деятельности сотрудников?
> 
> Хороший вопрос, думаю, стоит добавить отработанные часы, для этого наверное нужно еще добавить сущность "Месяцы" 😢

или убрать из ТЗ. Или расписание


> Бронирование по факту та же аренда, с возможностью отмены, но за час до начала срока аренды (бесплатно)

отмена бронирования не фиксируется? А, что будет, если я отменю за полчаса?

> > в чем проявляется связь между акциями и экземплярами техники (приведи пример акции)?
> 
> Например создается акция со временем от 21 сентября до 28 со скидкой на все устройства, в запросе это будет выглядеть как создание добавление в таблицу акции-экземпляр новых данных, вяжущихся к этой акции, соответственно, и ко всем экземплярам типа "экземпляры техники" (если бы акция была для отдельных типов техники, то она привязывала бы с условием "тип устройства = _такому-то_"). При вычислении цены на аренду, проверяются все привязанные к данному экземпляру акции-экземпляры, осуществляется переход на акцию и просматривается ее дата, если есть такие акции, которые все еще действуют, то цена за тариф умножается на коэффициент.

зачем для этого вычисления нужны данные? не проще ли пройтись по действующим акциям при определении цены? Твои вычисления построены очень неэффективно

**Comment by thisheavydyingsoul** [comment]
> желательно... А зарплата здесь каким боком? зачем она нужна?
> 
У меня в требованиях контроль за работой сотрудников, следовательно и содержание информации о них

> отмена бронирования не фиксируется? А, что будет, если я отменю за полчаса?
> 
Фиксируется, снимется оплата за первый час

> зачем для этого вычисления нужны данные? не проще ли пройтись по действующим акциям при определении цены? Хм, тогда акции будут отдельно от всех?

**Comment by wldmr-key** [comment]
> > желательно... А зарплата здесь каким боком? зачем она нужна?
> 
> У меня в требованиях контроль за работой сотрудников, следовательно и содержание информации о них

не вижу связи между зарплатой и контролем. Это единственный контроль, кстати? ))

> > отмена бронирования не фиксируется? А, что будет, если я отменю за полчаса?
> 
> Фиксируется, снимется оплата за первый час

и первый час за это железо никто не сможет сесть?

> Хм, тогда акции будут отдельно от всех?

тебя это пугает?

**Comment by thisheavydyingsoul** [comment]
> > > желательно... А зарплата здесь каким боком? зачем она нужна?
> > 
> > 
> > У меня в требованиях контроль за работой сотрудников, следовательно и содержание информации о них
> 
> не вижу связи между зарплатой и контролем. Это единственный контроль, кстати? ))

Вот я изменил требования под это)


> и первый час за это железо никто не сможет сесть?

Сможет, я только думаю, что тогда с этой бронью в базе данных делать, удалять? Во время прошлого семестра вроде говорили, что это плохо, чистить данные, но если мне не важно их хранение, тогда почему бы не удалить. Штрафов тем, кто бронирует не приходит - не будет, они ж первый час оплачивают.
> тебя это пугает?

Мне кто-то сказал, что вам такое не нравится)

**Comment by wldmr-key** [comment]
еще раз внимательно

> все ли атрибуты у тебя упомянуты в описании предметной области

> но если мне не важно их хранение

а деньги ты как считать будешь?

> > тебя это пугает?

> Мне кто-то сказал, что вам такое не нравится)

меня это настораживает, но никакого криминала в этом нет

**Comment by GeneralPechenka** [comment]
Про аренды и бронирования: я бы добавил статус как атрибут. Тогда бы у тебя система различала что забронировано, что уже арендуется. А в бронь можно также добавит время начала, и проверять, когда кто-то хочет отменить бронь и не заплатить клубу.

> Отзывы:
Дата и время публикации
Рейтинг (от 0 до 10)
Содержание

У тебя отзывы будут хранить пользователя, который его оставил, или нет? Это мб полезно, например, для фидбека.

> У меня в требованиях контроль за работой сотрудников, следовательно и содержание информации о них.

Зарплата - это результат работы сотрудника. Она учитываться не должна никем, кроме начальника и государства. А вот то, что они делали (или хотя бы что им разрешено делать), сколько работали и защита системы от их лапок - это, по-моему, стоит контролировать системой. Например, сотрудник Михаил Е. проработал 40 часов за неделю, оформил столько-то аренд и забронировал столько-то. Но он хотел сделать себе зарплату миллион (утрирую), и система ему заблокировала это действие, но он не сдался и сделал зп 99 999,99, и это спалил начальник в конце месяца, и оставил Михаила в подвале без еды и воды.

**Comment by thisheavydyingsoul** [comment]
> Про аренды и бронирования: я бы добавил статус как атрибут. Тогда бы у тебя система различала что забронировано, что уже арендуется. А в бронь можно также добавит время начала, и проверять, когда кто-то хочет отменить бронь и не заплатить клубу.

Слишком тяжело, а вот статус отменено или нет я припишу, правильно указали выше про счет денег

> У тебя отзывы будут хранить пользователя, который его оставил, или нет? Это мб полезно, например, для фидбека.

Конечно будут, они ж связаны с ними, но это концептуальная схема, внешних ключей тут нет
> > У меня в требованиях контроль за работой сотрудников, следовательно и содержание информации о них.

> Зарплата - это результат работы сотрудника... 

Зарплата фиксирована, как и количество часов, которые он должен отработать, для подсчета больничных и прочего надо очень усложнять систему, что мне не нравится, я изначально ее планировал больше для автоматизации клуба.
Сотрудники никак не влияют на аренды и тому подобное, там есть охранники и уборщики, только такого рода люди, ну и те, кто следят за их работой, типа админов

**Comment by GeneralPechenka** [comment]
> Зарплата фиксирована, как и количество часов, которые он должен отработать, для подсчета больничных и прочего надо очень усложнять систему, что мне не нравится, я изначально ее планировал больше для автоматизации клуба.
Сотрудники никак не влияют на аренды и тому подобное, там есть охранники и уборщики, только такого рода люди, ну и те, кто следят за их работой, типа админов

Зачем тебе там зарплата? Она всё равно должна считаться в бухгалтерии, потому что нужно вычитать 13%, платить отчисления на пенсии сотрудникам (если они устроены официально).

Вместо неё я бы лучше сделал логин и пароль для входа в систему, чтобы она могла знать, кто работает за компьютером.

=> при оформлении аренды или брони можно просто указывать, кто её оформил.

А для регулирования можно ввести права доступа. Например, 0 - уборщики и пр, которые не должны ничего делать, а 5 - администратор, который может делать в системе всё, что хочет.  И при выполнении чего-либо просто его проверять.

**Comment by GeneralPechenka** [comment]
По-моему мнению ты решил сделать систему, которая делает всё: и решает вопросы с арендой техники, и считает зарплату сотрудникам.  Может быть, стоит сконцентрироваться на чём-нибудь одном? Это совершенно разные задачи. 

А если там вся зарплата - оклад, то зачем её хранить именно в этой системе? Она не выполняет никакой функции, просто лежит в памяти. Тем более, обычно на таких работах зарплата рассчитывается из отработанных смен. И смысл потенциальному покупателю системы указывать эти данные, если они не несут никакой пользы?

**Comment by thisheavydyingsoul** [comment]
Она не считает зарплату никому, но хранит данные о сотрудниках, откуда ты вообще это взял?

> ...если они не несут никакой пользы?

Как не несут? Я буду каждого Васю брать себе на работу и не хранить о нем абсолютно никакой информации? Можно ж и про клиентов так же сказать, зачем мне их ФИО, мне от них только деньги считать надо.

**Comment by GeneralPechenka** [comment]
> Она не считает зарплату никому, но хранит данные о сотрудниках, откуда ты вообще это взял?

Читай внимательнее, что я пишу. Я не пишу о том, что она считает зарплату.

Окей, у тебя в бд будет храниться зарплата. Окей, она там нужна чисто посмотреть. 
Но работодатель должен с зп вычитать 13%, и платить государству. Ещё он должен делать отчисления в фонд социального страхования и много чего другого. Он будет это делать в тетрадке с калькулятором? Нет, у него для этого есть, чаще всего 1С, которая всё сама посчитала. А у тебя в системе зарплата только хранится и её можно только посмотреть, потому что она красивая.

Я это к тому, что у тебя эти данные просто лежат и никак полезно не используются, но и без них система не умрёт.

**Comment by wldmr-key** [comment]
> > ...если они не несут никакой пользы?
> 
> Как не несут? Я буду каждого Васю брать себе на работу и не хранить о нем абсолютно никакой информации?

Дмитрий прав, Кирилл неправ в этом вопросе. Одного оклада мало, даже если ты ИП (а ты - сеть филиалов!!!). Совершенно правильо замечено

> Зачем тебе там зарплата? Она всё равно должна считаться в бухгалтерии, потому что нужно вычитать 13%, платить отчисления на пенсии сотрудникам (если они устроены официально).

то есть, кадровый и бухгалтерский учет - это совершенно отдельные от твоей системы штучки

**Comment by thisheavydyingsoul** [comment]
Хм, тогда мне и сотрудники не нужны?

**Comment by thisheavydyingsoul** [comment]
Вот сейчас понял, что они не вписываются в саму систему ну просто никак, они есть в предметной области, безусловно, но система создается для того, чтобы максимально сократить их количество.

**Comment by wldmr-key** [comment]
нужны, как минимум, люди имеющие право изменять данные со стороны клуба и просматривать результаты его работы

**Comment by thisheavydyingsoul** [comment]
А как они должны изменять данные? Просматривать понятно, но для этого учет необязательно вести

**Comment by wldmr-key** [comment]
акции у тебя как появляются в системе? Новые виртуальные шлемы? Посетители вносят? ))

**Comment by thisheavydyingsoul** [comment]
Хорошее замечание

**Comment by thisheavydyingsoul** [comment]
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/09fa5d6b-17ee-4638-9ada-b0bee32d36f6)
Насколько безобразно это выглядит? И если сильно, то как с этим бороться? Вопрос не в логике данной схемы, я ее потом объясню, вопрос в самих соединительных линиях

**Comment by wldmr-key** [comment]
их наличие не так страшно, как может показаться в час ночи ))

Другое дело, что появившиеся аццкие связи, скорее всего, идут не к аккаунатам (см. антипаттерны), а к сотрудникам

**Comment by thisheavydyingsoul** [comment]
Подскажите пожалуйста, как этот антипаттерн называется

**Comment by thisheavydyingsoul** [comment]
Еще одна попытка: 
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/0aea747d-e15d-4e57-b688-bbd84f99b4ca)
Сущности и атрибуты, а также описание их связей:
1. Клиенты (их аккаунт), связаны с арендами (клиенты арендуют технику):
* ФИО
* Баланс
* Никнейм
* Логин
* Пароль
* Телефон
* Почта
* Аватарка

2. Аренды (связаны с техникой и отзывами, тут вроде логично):
* Статус
* Дата и время начала
* Дата и время окончания
* Итог

3.  Отзывы:
* Дата и время публикации
* Рейтинг (от 1 до 10)

4. Экземпляры техники, связаны с играми (чтобы узнавать установлены игры на экземплярах или нет), связаны с сотрудниками (кто принял и внес в БД, кто сделал последнее изменение), с филиалами (где находятся):
* Тип
* Состояние 
* Тариф дневной (руб/час)
* Тариф ночной (руб/час)

5. Игры связаны с сотрудниками так же, как и экземпляры с сотрудниками:
* Название

6. Филиалы связаны с сотрудниками, это указывает, где они работают:
* Адрес
* Рейтинг

7. Сотрудники (их аккаунты), связаны с акциями (создают их):
* ФИО
* Логин
* Пароль
* Телефон
* Почта

8. Акции:
* Дата начала
* Дата окончания
* ПК (да/нет)
* Консоли (да/нет)
* Шлемы ВР (да/нет)
* Тариф

**Comment by wldmr-key** [comment]
> Подскажите пожалуйста, как этот антипаттерн называется

полиморфные ассоциации

**Comment by wldmr-key** [comment]
> Отзывы

судя по картинке, отзыв можно написать на несколько аренд. Это так?

> кто сделал последнее изменение

это рискованная связь по двум причинам: пропадает предпоследнее изменение и непонятно, что изменялось. Впрочем, ты можешь сказать, что человек, вносящий изменение отвечает за всё (кстати, связь игры с экземпляром техники - это изменение?)

"Игры-экземпляры" - очень сомнительная сущность в концептуальной схеме. Многие ко многим правильнее

Откуда берется рейтинг филиала?

Про акции стоит подробнее написать в описании предметой облласти. Что они из себя представляют? Скидки? Фиксированные цены? на что распространяются? В любом случае атрибуты
> ПК (да/нет)
Консоли (да/нет)
Шлемы ВР (да/нет)

это тоже плохая идея - ты все-равно средствами SQL по-человечески не свяжешь значения этих столбцов с типами оборудования. Гораздо технологичней делать акции на тип оборудования

**Comment by thisheavydyingsoul** [comment]
> судя по картинке, отзыв можно написать на несколько аренд. Это так?
Вы правы, там должно быть 1 к 0
> > кто сделал последнее изменение
> 
> это рискованная связь по двум причинам: пропадает предпоследнее изменение и непонятно, что изменялось. Впрочем, ты можешь сказать, что человек, вносящий изменение отвечает за всё 

Да, я так и сделаю, также, возможно на уровне БД будет сам журнал логирования. (Не уверен на каких есть)

> Откуда берется рейтинг филиала?

Высчитывается на основе отзывов (сумма делится на количество). Стоит убрать как атрибут?
> Про акции стоит подробнее написать в описании предметой облласти. Что они из себя представляют? Скидки? Фиксированные цены? на что распространяются? В любом случае атрибуты...

Хм, а в таком случае дублированием это не будет? Одни и те же акции но для разных типов

**Comment by wldmr-key** [comment]
> Да, я так и сделаю

тогда это должно быть в требованиях к системе. И, кстати, если это так, то совершенно неважно, кто первым внес запись об оборудовании/игре 

> Стоит убрать как атрибут?

думаю, да. Зачем усложнять себе програмирование?

> Хм, а в таком случае дублированием это не будет? Одни и те же акции но для разных типов

нет, наоборот - программировать легче будет

Я плохо читал или атрибут состояние экземпляра не описан нигде?

**Comment by thisheavydyingsoul** [comment]
> тогда это должно быть в требованиях к системе. И, кстати, если это так, то совершенно неважно, кто первым внес запись об оборудовании/игре

Хорошо, имеет смысл, уберу тогда из схемы данную связь

> Я плохо читал или атрибут состояние экземпляра не описан нигде?

![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/ffbcf489-3f50-435e-9357-7ec58fc1a1a4)
Стоит дословно указать как состояние?

**Comment by wldmr-key** [comment]
Что такое статус/состояние неясно. И, конечно, стоит везде использовать один термин, а не путать всех

**Comment by thisheavydyingsoul** [comment]
Исправил в требованиях
