### ISSUE TITLE
Изготовить прототип или скетчи пользовательского интерфейса

### ISSUE THREAD

**Issue by thisheavydyingsoul** [thisheavydyingsoul/coursework#6]

**Comment by thisheavydyingsoul** [comment]
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/b5467437-d1fa-44b9-89c9-92721f20eccf)
Окно входа, для всех общее

**Comment by thisheavydyingsoul** [comment]
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/23d68469-2cd1-4721-96fb-268780c7b460)
Меню для посетителей клуба на пк

**Comment by thisheavydyingsoul** [comment]
Меню слева*

**Comment by thisheavydyingsoul** [comment]
Меню для посетителей клуба на пк
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/72d5d601-f9df-468f-9283-6e78643e93be)

**Comment by thisheavydyingsoul** [comment]
Это еще не все, понятное дело, продолжу скидывать позже

**Comment by wldmr-key** [comment]
меню для посетителей - а где можно забронировать?

**Comment by thisheavydyingsoul** [comment]
Пока не скинул, это будет на мобильное приложение (и чувствую я зря лезу в мобильные))))), а то будет так, что забронировать компьютер можно только с самого компьютера, не очень для посетителей, удобнее скачать)

**Comment by wldmr-key** [comment]
> и чувствую я зря лезу в мобильные))))),

сделай браузерное ))

> бронировать компьютер можно только с самого компьютера,

почему бы благородному дону не забронироать компьютер на завтра?

**Comment by thisheavydyingsoul** [comment]
Интерфейс пользователя:
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/00669140-4dd7-4b60-928a-4eb9274a92f6)

Интерфейс сотрудника:
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/c304db10-9abe-44ed-ad22-7ac5b371ed9f)

**Comment by wldmr-key** [comment]
может быть и так

**Comment by thisheavydyingsoul** [comment]
Тогда закрываю этот issue? Если что-то добавится, то будут дополнительные кнопки, а сейчас вроде как все

**Comment by wldmr-key** [comment]
конечно, ты его можешь закрыть, но пока никаких форм для ввода атрибутов и вывода полезной информации для посетителей/клуба я не увидел. Они будут?

**Comment by thisheavydyingsoul** [comment]
Да, будут, но каждое будет нужно продумывать отдельно, но уже с видимостью таблиц в БД

**Comment by thisheavydyingsoul** [comment]
Пришли мысли все же 
Настройка профиля клиента
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/bf892658-e1cf-4415-82af-65d48f0c0c1d)

А вот тут уже интереснее, строка поиска игр
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/2f2c775b-b59a-4971-b2bf-37f9be6496e4)
При нажатии на игру, выпадает такой список
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/78d8396a-9796-4295-82a5-6e0ce7a0aa19)


Продление аренды
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/f7bc4dc8-07f4-42e8-bb54-ab2599b810a2)
Часы и минуты

Бронирование (все же выделю в 2 отдельные кнопки)
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/dd19f003-49f0-488e-9479-dbb5767b8781)

История посещений
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/9cdbc0a9-cdf5-464f-a649-c3200a346b15)

Также будет еще кнопка пополнить баланс, там обычный ввод карты.

Разделю 2 интерфейса на 2 комментария лучше, чтобы было понятнее

**Comment by thisheavydyingsoul** [comment]
Внесение в БД нового устройства
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/12e5bea3-c0ea-478b-ae48-a60e562f5fe9)

При выборе изменения устройства
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/4f66b754-7746-413e-b2fa-491c13b75e14)

Добавление игр
![image](https://github.com/thisheavydyingsoul/coursework/assets/118654019/c6c047b5-7d26-4f7c-a628-b15bd0de3e20)
Изменение игр происходит точно так же

Настройки профиля аналогичны клиентским, за исключением некоторых вещей, которых нет у сотрудников

**Comment by wldmr-key** [comment]
неплохо. Не очень понято, что означает "забронировать игру" - ведь, она на нескольких устройствах...

я правильно понимаю, что в интерфейсе можно будет поставить игру на несколько устройств и, наоборот, поставить на стройство несколько игр?

я правильно понимаю, что на консоль и шлем нельзя будет поставить игру для ПК?

**Comment by thisheavydyingsoul** [comment]
> неплохо. Не очень понято, что означает "забронировать игру" - ведь, она на нескольких устройствах...

Что-то не вижу у себя такого

> я правильно понимаю, что в интерфейсе можно будет поставить игру на несколько устройств и, наоборот, поставить на стройство несколько игр?

 Да


> я правильно понимаю, что на консоль и шлем нельзя будет поставить игру для ПК?

Ну, это все ложится на плечи сотрудников, конечно, есть эксклюзивы, которые нельзя установить на ПК или другие платформы, но сотрудники не должны намеренно делать что-то, вводящее клиентов в заблуждение, да и большинство клиентов, при желании поиграть в какую-то игру, скорее всего, знают, на какой платформе они будет играть

**Comment by wldmr-key** [comment]
![image](https://github.com/thisheavydyingsoul/coursework/assets/12798933/166d5c7d-2a17-47e2-8dca-a20061d8c8df)

**Comment by thisheavydyingsoul** [comment]
Я может не понимаю, а при чем тут игры?

**Comment by thisheavydyingsoul** [comment]
Название тут у устройства

**Comment by wldmr-key** [comment]
> Название тут у устройства

тогда, это я ступил ))

**Comment by thisheavydyingsoul** [comment]
Ну, может у меня не очень понятно? Вдруг клиенту не будет тоже

**Comment by wldmr-key** [comment]
не, нормально. Я по диагонали смотрел все сразу - мог и перепутать
