### ISSUE TITLE
Введение

### ISSUE THREAD

**Issue by thisheavydyingsoul** [thisheavydyingsoul/coursework#8]

**Comment by thisheavydyingsoul** [comment]
Первые компьютерные клубы, или, интернет-кафе, появились не так давно, в рамках истории человечества, в 1994 году. Там люди могли выйти в интернет, поиграть в видеоигры, а также перекусить, выпить кофе или другие напитки. Раньше такие заведения позволяли людям, не желающим или не имеющим возможности приобретать достаточно дорогие устройства, доступно арендовать их и получать доступ в интернет. На сегодняшний день компьютерные клубы лишь набрали популярность: в нашей стране существует много подобных заведений и даже сетей интернет-кафе. В наше время комплектующие для ПК, консоли и другие устройства перестали быть доступны для покупки каждому человеку - в цене они могут достигать величины в несколько зарплат, а аппаратные требования для видеоигр растут с каждым годом. Но, посещение компьютерного клуба все так же оптимально в цене, как и было раньше. Киберкафе играют огромную роль в жизни современного игрового сообщества, они делают "гейминг" доступным каждому. Но также это сообщество постоянно расширяется, как в количестве людей, так и в разнообразии устройств и игр, именно поэтому возникает необходимость в создании автоматизированной системы работы компьютерных клубов.

Автоматизация в равной мере упрощает как работу администраторов клуба, так и времяпровождение клиентов в нем: становится легче вносить устройства в систему, видеть информацию о них, узнавать об акциях, искать игры и многое другое. Все это значительно ускоряет работу заведения, а также минимизирует контакты клиент-администратор, что избавляет сотрудников от части обязанностей. 

Основаниями для подтверждения актуальности темы курсовой являются:
1. Необходимость компьютерных клубов в повышении эффективности своей работы, изменении процессов, а также предоставлении доступа к информации для пользователей без участия администраторов, в связи с постоянным ростом игрового сообщества и появлением новых технологий. 
2. Полная автоматизация большинства процессов значительно ускорит работу клубов, а также позволит сотрудникам выполнять другую работу, что повысит её эффективность.
3. Упрощенные контроль финансов (вот не уверен стоит ли писать тут про финансы, я же учитываю, сколько пользователь платит за аренду, но это лишь часть от всего финансового оборота) и ведение статистики позволяют рационально подходить к вопросам о снятии устройств с учета или же, наоборот, их закупке, а также видеть удовлетворенность пользователей в виде рейтинга о клубе. 
4. Улучшение безопасности: всегда можно отследить кто и когда проводил время за данным устройством, что позволит, например, в случае поломки, отследить виновного и принять соответствующие меры. 

Целью курсовой работы является разработка система автоматизации работы клуба, которая помогает вести учет игр и устройств, позволяет просматривать информацию об устройствах, а также упрощает оформление или продление аренды.

**Comment by thisheavydyingsoul** [comment]
Вопрос не по теме введения: что, если в процессе разработки (на любом из последующих этапов), будет необходимо ввести какую-то другую сущность, или же, наоборот, убрать уже существующую? Необходимо ли будет при этом изменять концептуальную схзему?

**Comment by wldmr-key** [comment]
вполне
Рад, что ты преодолел врожденную лаконичность ))

**Comment by wldmr-key** [comment]
> Вопрос не по теме введения: что, если в процессе разработки (на любом из последующих этапов), будет необходимо ввести какую-то другую сущность, или же, наоборот, убрать уже существующую? Необходимо ли будет при этом изменять концептуальную схему?

конечно

**Comment by thisheavydyingsoul** [comment]
> вполне Рад, что ты преодолел врожденную лаконичность ))
Тут скорее наоборот, я боюсь расписать больше чем нужно, отсюда и стремление сделать меньше, а введение я посмотрел, у других вполне себе большое
